config/routes.rb
Rails.application.routes.draw do
  get 'releases/new'
  get 'releases/index'
  get 'releases/edit'
  get 'releases/show'
  root to: "homes#top"

  get '/profile', to: 'homes#profile'

   resources :profiles, only: [:new,:show,:create,:edit,:update,:destroy]

  resources :infos, only: [:new,:show,:create,:edit,:update,:index,:destroy]

  resources :releases, only: [:new,:create,:index,:show,:edit,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :release
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
  has_many :musics, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true
  has_one_attached :release_image

  private

  def release_image_attached?
    release_image.attached?
  end

  def attach_default_image
    file_path = Rails.root.join('app/assets/images/no_image1.jpg')
    release_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @infos = Info.order('id DESC').limit(3)
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def new
    @info = Info.new
  end

  def create
    @info = Info.new(info_params)
    if @info.save
      redirect_to info_path(@info)
    else
      render "new"
    end
  end

  def show
    @info = Info.find(params[:id])
  end

  def index
    @info = Info.new
    @info_list = Info.all
  end

  def edit
    @info= Info.find(params[:id])
  end

  def update
    @info = Info.find(params[:id])
    if @info.update(info_params)
      redirect_to info_path(@info), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy
    redirect_to "/infos"
  end



  private
  def info_params
    params.require(:info).permit(:title,:body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path(@profile)
    else
      render "new"
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile= Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to "/"
  end



  private
  def profile_params
    params.require(:profile).permit(:profile)
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  def new
    @release = Release.new
    @music = @release.musics.build ##親モデル.子モデル.buildで子モデルのインスタンス作成
  end

  def create
    @release = Release.new(release_params)
    if @release.save
      redirect_to release_path(@release)
    else
      render :new
    end
  end

  def show
    @release = Release.find(params[:id])
    @sum = 0
  end

  def edit
    @release = Release.find(params[:id])
  end

  def update
    @release = Release.find(params[:id])
    if @release.update(release_params)
      redirect_to release_path(@release)
    else
      render :edit
    end
  end

  private

  def release_params
    params.require(:release).permit(:sub_title, :main_title, :release_day, :release_image, :detail,
                                  musics_attributes:[:id, :release_id, :music_title, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/homes/profile.html.erb
<div class="container">
<h1>
  ■PROFiLE
</h1>

<h5>
  LiSA(リサ)
岐阜県出身。6 月24 日生まれ。

'10年春より放送されたTV アニメ「Angel Beats!」の劇中バンド「Girls Dead Monster（通称︓ガルデモ）」2代目ボーカル・ユイ役の歌い手に抜擢され、ガルデモ名義でのシングル・アルバム累計40万枚以上をセールスし、人気を集める。'11 年春にミニアルバム「Letters to U」にてソロデビュー。
その後、TVアニメ「Fate/Zero」、「ソードアート・オンライン」、「魔法科高校の劣等生」、「鬼滅の刃」など数々の人気作品の主題歌を担当し、国内のみならず世界中にてヒットを記録。
‘19年4月に配信開始した楽曲「紅蓮華」は、配信直後に数々のデイリーチャートを席巻、配信デイリーチャートにて38冠を達成、“平成最後・令和最初”の週間デジタルシングル(単曲)で首位を獲得。同年末には「第70回NHK紅白歌合戦」への初出場を果たす。
‘20年10月には、アルバム「LEO-NiNE」とシングル「炎」を同時リリースし、オリコンデイリーアルバム、シングルランキング（10/13付）にて、“W1位”を獲得。
‘20年末にはTBS「第62回輝く！日本レコード大賞」にて、「日本レコード大賞」を獲得、さらに’21年末には3年連続となる「第72回NHK紅白歌合戦」への出場を果たした。
圧倒的な熱量を持つパフォーマンスと歌唱力、ポジティブなメッセージを軸としたライブは瞬く間に人気を集め、アニソンシーンにとどまらず、数多くのロックフェスでも活躍するライブアーティストとして、その存在感を示している。

座右の銘：今日もいい日だっ。

<ラブレターの送り先>
〒141-8569
東京都品川区上大崎2-13-30 OAK目黒1F~2F
株式会社ソニー・ミュージックアーティスツ内
『LiSA』宛まで。

※飲食物・植物・生物など、現金、金券類(ギフト券・チケットなど)、危険物は受け取ることができません。
</h5>
</div>

app/views/homes/top.html.erb
<div class ="container">
  <div class="row mt-3">
    <div class="col-4 d-flex align-items-end">
      <%= image_tag 'bn_EveBirth.jpg',class:"img1" %>
    </div>
    <div class="col-8">
      <%= image_tag 'img_main.jpg',class:"img1" %>
    </div>
  </div>
  <div class="row mt-5 p-5 top-info">
    <div class="col-12 text-light">
    <h1 class="mb-3">INFORMATiON</h1>
    <% @infos.each.with_index(3) do |info| %>
      <div class="row">
        <div class="col-2"></div>
          <p>
            <%= link_to info_path(info.id)  do %>
              <%= info.created_at %>
              <%= info.title %>
            <% end %>
          </p>
      </div>
    <% end %>
    <%= link_to "/infos" do %>
    more
    <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-12 text-center">
      <h1>MOVIE</h1>
    </div>
  </div>
  <div class="row mt-3 mb-5">
    <div class="col-4 text-center">
      <iframe width="350" height="100%" src="https://www.youtube.com/embed/5whFTc6SaI8" title="YouTube video player"
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen></iframe>
      <div class="mt-3">
        LiSA『白金』</br>
        -MUSiC CLiP-
      </div>
    </div>
    <div class="col-4 text-center">
      <iframe width="350" height="100%" src="https://www.youtube.com/embed/yGcm81aaTHg" title="YouTube video player"
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen></iframe>
      <div class="mt-3">
        LiSA『明け星』</br>
        -MUSiC CLiP-
      </div>
    </div>
    <div class="col-4 text-center">
      <iframe width="350" height="100%" src="https://www.youtube.com/embed/Ff7k1zxBe1I" title="YouTube video player"
      frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen></iframe>
      <div class="mt-3">
        LiSA『往け』</br>
        -MUSiC CLiP-
      </div>
    </div>
  </div>
</div>

app/views/infos/index.html.erb
<div class="container">
  <div class="m-5">
    <div class="row mt-5 pt-5">
      <div class="col-12">
        <h1 class="text-center mb-0">INFO</h1>
        <p class="text-center">LiSA</p>
      </div>
    </div>
    <hr class="style6">
    <% @info_list.each do |info| %>
      <%= link_to info_path(info.id) do %>
        <div class="row m-3">
          <div class="col-2">
            <%= info.created_at %>
          </div>
          <div class="col-8">
            <%= info.title %>
          </div>
          <div class="col-2">
            {INFO}
          </div>
        </div>
        <hr class="style6">
      <% end %>
    <% end %>
  </div>
</div>

app/views/infos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mb-5">
      <h2 class="text-center light2 mt-5 ml-5 col-8">新規INFO投稿</h2>
    </div>
  </div>

  <%#エラー文%>
  <% if @info.errors.any? %>
    <%= @info.errors.count %>件のエラーが発生しました
    <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-10 mb-5 offset-2">
      <%= form_with model: @info, local: true do |f| %>
        <form>
          <div class="form-group col-xs-9">
            <%= f.label :"INFOタイトル", class: "col-sm-2 light" %>
            <%= f.text_field :title, placeholder: "INFOタイトル", class: "col-sm-6 p-1" %>
          </div>
          <div class="form-group col-xs-9">
            <%= f.label :詳細, class: "col-sm-2 align-top light" %>
            <%= f.text_area :body, placeholder: "ここに内容を記述します", class: "col-sm-6 p-1", rows:"20" %>
          </div>
          <div class="form-group col-10 text-center">
            <%= f.submit "投稿", class: "btn btn-success col-sm-2" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/infos/show.html.erb
<div class="container">
  <div class="m-5">
  <div class="row mt-5 pt-5">
    <div class="col-12">
      <h1 class="text-center mb-0">INFO</h1>
      <p class="text-center">LiSA</p>
    </div>
  </div>
  <div class="row">
    <%= link_to "削除", info_path(@info), method: :delete %>
  </div>
  <div class="row mt-5 pt-5">
    <%= @info.created_at %>{NEWS}
  </div>
  <div class="row m-4">
    <h1><%= @info.title %></h1>
  </div>
  <hr class="style6">
  <div class="row m-4 mb-5">
    <p>
      <%=safe_join(@info.body.split("\n"),tag(:br))%>
    </p>
  </div>
  <hr class="style6">
  <div class="row">
    <h5 class="col-12 text-center mt-5 pt-5 mb-5 pb-5">
      <%= link_to "←　back to index", "/infos", class: 'text-dark' %>
    </h5>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
<div class="text-center mt-5">
  <%= image_tag 'logo1.png', class: "img3" %>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
<header class="mt-3 mb-3 pb-0">
  <nav>
    <a class="navbar-brand" href="/" data-turbolincks="false"><%= image_tag 'logo1.png', class: "img3" %></a>
    <div id="sp-menu">
      <ul>
        <div class="row mt-5">
          <div class="col-2"></div>
          <div class="col-4 mt-5">
        <li><a href="/">TOP</a></li>
        <li><a href="/infos">INFORMATiON</a></li>
        <li><a href="/profiles/1">PROFiLE</a></li>
        <li><a href="#">DiSCOGRAPHY</a></li>
        <li><a href="#">LiVE</a></li>
        <li><a href="#">MEDiA</a></li>
        </div>
        <div class="col-4 mt-5">
        <li><a href="#">LiNK</a></li>
        <li><a href="#">GOODS</a></li>
        <li><a href="#">FROM LiSA</a></li>
        <li><a href="#">MAiL</a></li>
        <li><a href="#">FAN CLUB</a></li>
        </div>
        <div class="col-2"></div>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger mr-5 pr-5" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
  </nav>
</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mb-5">
      <h2 class="text-center light2 mt-5 ml-5 col-8">新規PROFiLE投稿</h2>
    </div>
  </div>

  <%#エラー文%>
  <% if @profile.errors.any? %>
    <%= @profile.errors.count %>件のエラーが発生しました
    <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-10 mb-5 offset-2">
      <%= form_with model: @profile, local: true do |f| %>
        <form>
          <div class="form-group col-xs-9">
            <%= f.label :"PROFiLE", class: "col-sm-2 light" %>
            <%= f.text_area :profile, placeholder: "PROFiLE", class: "col-sm-6 p-1", rows:"20" %>
          </div>
          <div class="form-group col-10 text-center">
            <%= f.submit "投稿", class: "btn btn-success col-sm-2" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="m-5">
  <div class="row mt-5 pt-5">
    <div class="col-12">
      <h1 class="text-center mb-0">PROFiLE</h1>
      <p class="text-center">LiSA</p>
    </div>
  </div>
  <div class="row">
    <%= link_to "削除", info_path(@profile), method: :delete %>
  </div>
  <hr class="style6">
  <div class="row m-4 mb-5">
    <p>
      <%=safe_join(@profile.profile.split("\n"),tag(:br))%>
    </p>
  </div>
  <hr class="style6">
  <div class="row">
    <h5 class="col-12 text-center mt-5 pt-5 mb-5 pb-5">
      <%= link_to "←　back to index", "/", class: 'text-dark' %>
    </h5>
  </div>
</div>
</div>

app/views/releases/_music_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    <div class="col-5"><%= f.text_field :music_title, class: "form-control", placeholder: "曲名" %></div>
    <div class="col-1 px-0 w-auto">
      <%= link_to_remove_association "削除", f %>
    </div>
  </div>
</div>

app/views/releases/edit.html.erb
<h1>Releases#edit</h1>
<p>Find me in app/views/releases/edit.html.erb</p>

app/views/releases/index.html.erb
<h1>Releases#index</h1>
<p>Find me in app/views/releases/index.html.erb</p>

app/views/releases/new.html.erb
<div class="container">
  <div class="m-5">
  <div class="row mt-5 pt-5">
    <div class="col-12">
      <h1 class="text-center mb-0">RELEASE</h1>
      <p class="text-center">LiSA</p>
    </div>
  </div>
<div class="recipe-post">
  <%= form_with(model: @release, url: releases_path, local: true) do |f| %>

    <div class="recipe-ingredients">
      <div class="row">
        <%= f.label :投稿画像, class: "col-sm-2 light" %>
            <%= f.file_field :release_image, accept: "image/*" %>
      </div>
      <div class="row">
        <%= f.label :サブタイトル, class: "col-sm-2 light" %>
        <%= f.text_field :sub_title, placeholder: "サブタイトル", class: "col-sm-6 p-1" %>
      </div>
      <div class="row">
        <%= f.label :メインタイトル, class: "col-sm-2 light" %>
        <%= f.text_field :main_title, placeholder: "メインタイトル", class: "col-sm-6 p-1" %>
      </div>
      <div class="row">
        <%= f.label :リリース日, class: "col-sm-2 light" %>
        <%= f.text_field :release_day, placeholder: "リリース日", class: "col-sm-6 p-1" %>
      </div>
      <div class="row">
        <%= f.label :詳細, class: "col-sm-2 light" %>
        <%= f.text_field :detail, placeholder: "詳細", class: "col-sm-6 p-1" %>
      </div>
      <div class="mx-auto">
        <%= f.fields_for :musics do |t| %>
          <%= render "releases/music_fields", f: t %>
        <% end %>
      </div>

      <div id="detail-association-insertion-point"></div>

      <div class="col-10 mx-auto mt-2">
        <%= link_to_add_association "+フォームを追加", f, :musics,
        class: "btn btn-secondary btn-block",
        data: {
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'before'
        }%>
      </div>
    </div>
    <div class="row text-center">
      <%= f.submit "投稿", class: "btn btn-success col-sm-2" %>
    </div>
  <% end %>
</div>
</div>

app/views/releases/show.html.erb
<div class="container">
  <div class="m-5">
  <div class="row mt-5 pt-5">
    <div class="col-12">
      <h1 class="text-center mb-0">RELEASE</h1>
      <p class="text-center">LiSA</p>
    </div>
  </div>
  <div class="row mt-5 pt-5">
    <div class="col-6 pr-5">
    <%= image_tag @release.release_image, class: "img1" if @release.release_image .present? %>
    </div>
    <div class="col-6 pl-5">
      <div class="row">
        <%= @release.sub_title %>
      </div>
      <h2 class="row mt-3">
        <%= @release.main_title %>
      </h2>
      <div class="row mt-3">
        <%= @release.release_day %>
      </div>
      <div class="row">
        <%= @release.detail %>
      </div>
      <div class="mt-3">
      <% @release.musics.each do |music| %>
        <div class="row">
          <h1 class="col-1">
            <%= @sum += 1 %>
          </h1>
          <h3 class="col-6 mt-2">
            <%= music.music_title %>
          </h3>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <%= link_to "編集", edit_release_path(@release) %>
  </div>
  <div class="row">
    <%= link_to "削除", release_path(@release), method: :delete %>
  </div>
  <div class="row">
    <h5 class="col-12 text-center mt-5 pt-5 mb-5 pb-5">
      <%= link_to "←　BACK", "/releases", class: 'text-dark' %>
    </h5>
  </div>
</div>